import Head from 'next/head'
import { Hero } from '@/components/Hero'
import { Header } from '@/components/Header'
import { How } from '@/components/How'
import { What } from '@/components/What'
import { Expert } from '@/components/Expert'
import { Contact } from '@/components/Contact'
import { Footer } from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tapajós - Carbon Credits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <How />
      <What />
      <Expert />
      <Contact />
      <Footer />
      

    </>
  )
}
